version: "3"  # composer version

services:
  app:
    build:
      context: .  # current directory
    ports:
      - "8000:8000"
    volumes:  # pull changes in real time to the container
      - ./app:/app
    command: >  # command that runs the service
      sh -c "python manage.py runserver 0.0.0.0:8000"  # using shell
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=somepasswordthathastobereplaced
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=somepasswordthathastobereplaced
